# Generated by Django 5.1.4 on 2025-01-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(),
        ),
    ]
